name: hand_made_new
description: application for foods

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"
   

dependencies:
  introduction_screen: ^2.1.0
  smooth_page_indicator: ^1.0.0+2
  google_nav_bar: ^5.0.5
  flutter_bloc: ^8.0.0
  bloc: ^8.0.1
  google_maps_flutter: ^2.1.1
  image_picker: ^0.8.4+4
  simple_gradient_text: ^1.2.2
  conditional_builder: ^1.0.2
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.9
  path_provider: ^2.0.7
  geolocator: ^8.0.0
  permission_handler: ^8.3.0
  device_preview: ^1.0.0
  url_launcher: ^6.0.20
  font_awesome_flutter: ^9.2.0
  video_player: ^2.2.14
  chewie: ^1.1.0
  responsive_framework: ^0.1.7
  cached_network_image: ^3.2.0
  rxdart: ^0.27.3
  bloc_pattern: ^3.0.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  #firebase
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  firebase_messaging: ^11.2.14





dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/applogo.png"

  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4



flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/applogo.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages



  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
